### ISSUE TITLE
Attribute formats can be "color" to prevent misuse

### ISSUE THREAD

**Issue by burcugen** [mondayhero/android-platform-support#1]
**Describe the bug**
Attribute formats can be "color" to prevent misuse /cc Thanks to @necatisozer 

**To Reproduce**
1. Go to 'Export Code'
2. Click on 'Android Studio Project.'
3. Open to 'attrs.xml' file
4. See color attributes format is "reference".

**Expected behavior**
Color attributes format should be "color" instead of "reference". Reference is a general format.

**Screenshots**
<img width="367" alt="Screen Shot 2020-04-21 at 18 26 43" src="https://user-images.githubusercontent.com/5956735/79981794-f1d99a80-84ad-11ea-92d4-f99144ec3027.png">

**Mac App (please complete the following information):**
 - OS: All
 - Version All

**Additional context**
-

**Comment by BurakAkten** [comment]
Fixed with version 1.3.1.
