### ISSUE TITLE
Design Overview, variable type should be correct. 

### ISSUE THREAD

**Issue by burcugen** [mondayhero/android-platform-support#4]
**Describe the bug**
On Design Overview, hovered item programming type shown as UIImageView it should be ImageView according to Android /cc @necatisozer 

**To Reproduce**
1. Go to Any Screen under Android Project.
2. Go mouse cursor over any view(item) on Design Preview.
3. Click the item.
4. New info window title is UIImageView.

**Expected behavior**
On Design Overview, hovered item programming type shown as UIImageView it should be ImageView according to Android 

**Screenshots**
<img width="303" alt="Screen Shot 2020-04-21 at 16 07 56" src="https://user-images.githubusercontent.com/5956735/79984199-81347d00-84b1-11ea-93d9-a9a020ef6669.png">

**Mac App (please complete the following information):**
 - OS: Any
 - Version Any

**Comment by BurakAkten** [comment]
Fixed with version 1.3.1.
